### ISSUE TITLE
Changes to a route that happen synchronously to a route update can get lost

### ISSUE THREAD

**Issue by rictic** [PolymerElements/carbon-route#44]
This is because of the `_skipMatch` property, causing upstream routes to ignore changes to their `tail` properties, even if they're legitimate. We should be able to get rid of `_skipMatch` or double checking the values of `data` and `tail` after we set `_skipMatch` to false in `__tryToMatch`.

**Comment by TimvdLippe** [comment]
A similar issue has been discovered in #77 where updating a `data` value (and consequently updating the corresponding route) resulted in a loss of the `tail` property. I have solved this in the PR by explicitly calling `__tryToMatch` in the observer.

However, this `_skipMatch` is still problematic. If I understand the code correctly, the reason it exists is because of the clear connection between the different properties. However, the observers are required to observe changes from the outside (via the data-bindings).

Therefore I propose to separate the internal and external observers as follows: use an object `_internal` for all internal calculations. This object will always have the correct information, presumably when `__tryToMatch` has been called. The observers still observe the actual properties (e.g. no breaking changes) to update the `_internal` object when data-bindings are changed. Then whenever the element finished calculating all the new properties (data, tail and route) it calls a method which modifies the values but obviously does not trigger the inner observers. This could still be done by having a `_skipObserver` property.
