### ISSUE TITLE
Confusing README

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/carbon-route#55]
The readme says that (carbon location) https://elements.polymer-project.org/elements/carbon-route-converter?foo=bar&baz=qux produces a route of:
```
{
  prefix: '',
  path: '/elements/carbon-route-converter'
}
```

Thus ignoring queries.

But (carbon route convertor) says that: 

https://elements.polymer-project.org/elements/carbon-route-converter?foo=bar&baz=qux:

has a route of:
```
{
  prefix: '',
  path: '/elements/carbon-route-converter',
  queryParams: {
    foo: 'bar',
    baz: 'qux'
  }
}
```

I assume that it only has this route object when using iron-location and not carbon-location but that is not clear.

Also, why does 

```
<carbon-route-converter
    path="{{path}}"
    query-params="{{queryParams}}"
    route="{{route}}">
</carbon-route-converter>
<carbon-route route='{{route}}' pattern='/:page' data='{{data}}'>
```

carbon-route-convertor need the queryParams at all, when carbon-location assumes a route without query params (unless the use-hash-as-path is used)?

I think this could be made more clear, and the readme could benefit from more examples using queries which is actually not that uncommon a use-case.

**Comment by e111077** [comment]
@kenchris We will update the documentation accordingly, but I want to address your questions directly first.

Thanks for pointing out the discrepancy between the README and `carbon-route-converter` specs of the `route` object. The README is correct, and the documentation in `carbon-route-converter` is outdated.

`carbon-route-converter` requires `queryParams` because the route object has a private `__queryParams` property that is linked to the public `queryParams` object. We chose not to express this in the documentation as this is not in the public API for the `route` object (it was public in a prior implementation hence the first issue you noticed). Here is an example `route` object with the private API exposed given the url `https://elements.polymer-project.org/elements/carbon-route-converter?foo=bar&baz=qux`:

    {
      prefix: '',
      path: '/elements/carbon-route-converter'
      __queryParams: { foo:'bar', baz:'qux'}
    }

`carbon-location` uses this private property so that between `carbon-location`s and `carbon-route`s you only have to pass the `route` object instead of both the `route` and `queryParams` object.

**Comment by kenchris** [comment]
OK, thanks for the explanation.
