### ISSUE TITLE
Less confusing syntax sugar

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/carbon-route#90]
In most cases you don't need the `route="{{route}}"` attribute thing that right now you have to spam all over the place.

Example how I think it should look like instead:
```
<carbon-location>
  <carbon-route pattern="/tabs/:tabName" data="{{data}}"></carbon-route>
</carbon-location>
```

or just

```
 <carbon-route pattern="/tabs/:tabName" data="{{data}}"></carbon-route>
```

and call `carbon-location` internally if the `route` attribute is not specified

**Comment by TimvdLippe** [comment]
@gertcuykens I have not needed more than two `<carbon-location>` in my applications. What is your setup that requires you to do so?

**Comment by thesuperzapper** [comment]
Not OP, but I have needed two `<carbon-location>`.

One was to control the main URL, and the other was to control the stuff
after the "#".

**Comment by rictic** [comment]
It would be nice to have a little less boilerplate, but philosophically `carbon-route` is taking a stand that simple, standard, and explicit is better than complex, special, and implicit, . A big win of `carbon-route` is that it's easy to understand and debug because it's not doing anything magical, most of the work of routing is turned into simple and standard data binding.
