### ISSUE TITLE
Hash as path includes query parameters in path

### ISSUE THREAD

**Issue by dhesson** [PolymerElements/carbon-route#96]
### Description
Carbon location's use-hash-as-path does not separate query parameters from the path itself, causing carbon-route pattern matches to fail.  An example URI that works with default behavior, but no longer works once useHashAsPath is set to true, would be the URI `http://localhost/search?p=12312`.  Once we introduce a hash and the URI becomes `http://localhost/#/search?p=12312`, use hash as path will resolve a path of `"/search?p=12312"`, whereas a browser would interpret such as a path as `"/search"`, and `"p=12312"` would be the (search) params.  The pattern in this case was "/:page".

### Expected outcome

I would expect URIs such as `http://localhost/#/search?p=12312` to match carbon route of `"/:page"`when using `<carbon-location use-hash-as-path ...>`

### Actual outcome

Carbon attempts to match the entire hash value, causing the match fail.

### Live Demo

http://plnkr.co/edit/sS4cV5?p=preview

### Steps to reproduce

See live demo?

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by rictic** [comment]
Our gambit for this right now is to always put the query params in the `query` section of the url, so instead of `http://localhost/#/search?p=12312` you'd do `http://localhost/?p=12312#/search`. It looks slightly weird, but it works, and it gives a few advantages. The biggest is that we're can use entirely standard, browser-native URL parsing.

As far as I'm aware major static file servers ignore query params, so you're unlikely to run into trouble with the server. Browser support is very solid as well, any browser that works with Polymer will support using real query params and updating them via either links or data-binding.

If there's a use case that doesn't work with native query params then that's something we can consider. It's also worth noting that you can roll your own `carbon-location` to support custom URL encodings. We've factored the pieces out pretty well so it's an incredibly tiny amount of code if you do want to customize it.

**Comment by rictic** [comment]
Closing this for now, but please feel free to push back if you've got a use case that can't support proper query params.

**Comment by eitch** [comment]
I don't know if this is a bad use-case, but my use-case is that i use app-route in iron-pages and currently this works nice as the page never reloads when i navigate. Now if i want to use the hash and change the hash, then the whole page is reloaded in the browser, thus this would be a use-case where i would like the query to come from the hash after the actual path.

I hope this makes sense.

**Comment by rictic** [comment]
The whole page reloads? That shouldn't happen. What are you using to initiate the url change, the user clicking on a link?
